<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Rekapitulasi Surat Jalan</title>
    <style>
        /* CSS STANDAR LAPORAN CETAK (DOMPDF) */
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 10pt; /* Ukuran font standar dokumen */
            color: #333;
        }
        
        /* HEADER HALAMAN */
        .header {
            width: 100%;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 16pt;
            text-align: center;
            text-transform: uppercase;
        }
        .header p {
            margin: 2px 0 0 0;
            font-size: 9pt;
            text-align: center;
        }
        .meta-info {
            font-size: 8pt;
            text-align: right;
            margin-top: 5px;
            font-style: italic;
        }

        /* TABEL DATA */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        th, td {
            border: 1px solid #000; /* Garis hitam tegas */
            padding: 6px 8px;
            vertical-align: middle;
        }

        th {
            background-color: #2C3E50; /* Header Gelap Sesuai Excel */
            color: #ffffff;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 9pt;
            text-align: center;
        }

        td {
            font-size: 9pt;
        }

        /* UTILITY CLASSES */
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .text-uppercase { text-transform: uppercase; }
        .font-bold { font-weight: bold; }

        /* STATUS BADGE SIMULATION FOR PDF */
        .status-ok { color: green; font-weight: bold; }
        .status-pending { color: red; font-weight: bold; }

        /* FOOTER */
        .footer {
            position: fixed; 
            bottom: -30px; 
            left: 0px; 
            right: 0px;
            height: 50px; 
            font-size: 8pt;
            text-align: right;
            color: #555;
            border-top: 1px solid #ccc;
            padding-top: 5px;
        }

        /* ZEBRA STRIPING (Opsional agar mudah dibaca) */
        tr:nth-child(even) { background-color: #f9f9f9; }
    </style>
</head>
<body>

    {{-- HEADER --}}
    <div class="header">
        <h1>Laporan Rekapitulasi Surat Jalan</h1>
        <p>INTERNAL DOCUMENT &bull; DEPARTMENT LOGISTIK</p>
        <div class="meta-info">
            Dicetak pada: {{ \Carbon\Carbon::now()->format('d F Y H:i:s') }}
        </div>
    </div>

    {{-- TABEL --}}
    <table>
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="15%">No Surat Jalan</th>
                <th width="12%">No PPI</th>
                <th width="12%">No PO</th>
                <th width="10%">Tanggal</th>
                <th width="10%">Jenis</th>
                <th width="8%">Jml Item</th>
                <th width="10%">Status BAST</th>
                <th>Keterangan</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $item)
            <tr>
                <td class="text-center">{{ $loop->iteration }}</td>
                <td class="text-uppercase font-bold">{{ $item->no_sj }}</td>
                <td class="text-uppercase text-center">{{ $item->no_ppi ?? '-' }}</td>
                <td class="text-uppercase text-center">{{ $item->no_po ?? '-' }}</td>
                <td class="text-center">{{ \Carbon\Carbon::parse($item->tanggal_input)->format('d/m/Y') }}</td>
                <td class="text-center text-uppercase">{{ $item->jenis_surat_jalan }}</td>
                <td class="text-center">{{ $item->details_count }}</td>
                
                <td class="text-center">
                    @if($item->is_bast_submitted)
                        <span class="status-ok">SUDAH</span>
                    @else
                        <span class="status-pending">BELUM</span>
                    @endif
                </td>
                
                <td>{{ $item->keterangan ?? '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    {{-- SUMMARY SINGKAT DI BAWAH --}}
    <div style="margin-top: 20px; font-size: 10pt;">
        <strong>Total Dokumen:</strong> {{ $data->count() }} Surat Jalan <br>
        <strong>Dicetak Oleh:</strong> {{ auth()->user()->nama ?? 'Sistem' }}
    </div>

    {{-- FOOTER HALAMAN (Page Numbering biasanya otomatis oleh Browser/PDF Reader, tapi ini footer teks) --}}
    <footer class="footer">
        Confidential Document | Generated by System
    </footer>

</body>
</html>