@extends('layouts.app') 

@section('title', $title) 

@section('content')
<div class="container-fluid">

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ $title }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3 bg-primary">
            <h6 class="m-0 font-weight-bold text-white">
                <i class="fas fa-file-alt mr-1"></i> Form Pengajuan PPI
            </h6>
        </div>
        
        <div class="card-body p-0"> 
            @if ($errors->any())
                <div class="alert alert-danger m-3">
                    <strong><i class="fas fa-exclamation-triangle"></i> Perhatian!</strong>
                    <ul class="mb-0 pl-3">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('pengguna.ppi.store') }}" method="POST" enctype="multipart/form-data" id="formPpi">
                @csrf
                
                <div class="row no-gutters">
                    
                    {{-- KOLOM KIRI: INFO TIKET --}}
                    <div class="col-lg-4 bg-light border-right border-bottom p-4">
                        <h6 class="font-weight-bold text-primary mb-3">Info Tiket</h6>
                        
                        <div class="form-group mb-2">
                            <label class="small text-muted mb-0">Tanggal Request</label>
                            <div class="font-weight-bold text-dark">{{ date('d F Y') }}</div>
                        </div>

                        <div class="form-group mb-2">
                            <label class="small text-muted mb-0">No. PPI</label>
                            <div class="font-weight-bold text-dark">
                                <span class="badge badge-secondary">Generated by System</span>
                            </div>
                        </div>

                        <div class="form-group mb-0">
                            <label class="small text-muted mb-0">Pemohon</label>
                            <div class="font-weight-bold text-dark">
                                <i class="fas fa-user-circle mr-1"></i> {{ Auth::user()->name }}
                            </div>
                        </div>
                    </div>

                    {{-- KOLOM KANAN: INPUT FORM --}}
                    <div class="col-lg-8 p-4">
                        <h6 class="font-weight-bold text-primary mb-3">Detail Kerusakan / Permintaan</h6>

                        <div class="form-group">
                            <label class="font-weight-bold text-dark">Perangkat <span class="text-danger">*</span></label>
                            <input type="text" name="perangkat" class="form-control form-control-lg" 
                                   placeholder="Contoh: Printer Epson L360" 
                                   value="{{ old('perangkat') }}" required>
                        </div>

                        <div class="form-group">
                            <label class="font-weight-bold text-dark">Deskripsi Masalah / Kerusakan <span class="text-danger">*</span></label>
                            <textarea name="ba_kerusakan" class="form-control" rows="4" 
                                      placeholder="Jelaskan detail kendala yang dialami..." required>{{ old('ba_kerusakan') }}</textarea>
                        </div>

                        <div class="form-group">
                            <label class="font-weight-bold text-dark">Catatan Tambahan <small class="text-muted">(Opsional)</small></label>
                            <textarea name="keterangan" class="form-control" rows="2" 
                                      placeholder="Catatan lain jika ada...">{{ old('keterangan') }}</textarea>
                        </div>

                        <div class="form-group">
                            <label class="font-weight-bold text-dark">Foto / Dokumen Pendukung</label>
                            <div class="custom-file">
                                <input type="file" name="file_ppi" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">Pilih file...</label>
                            </div>
                            <small class="text-muted mt-1 d-block">Maksimal 2MB (JPG, PNG, PDF)</small>
                        </div>

                        <hr class="my-4">

                        {{-- AREA TANDA TANGAN (BARU) --}}
                        <div class="form-group">
                            <label class="font-weight-bold text-dark">Tanda Tangan Pemohon <span class="text-danger">*</span></label>
                            <div class="card bg-light border-0">
                                <div class="card-body text-center p-3">
                                    <div style="border: 2px dashed #aaa; background: #fff; display: inline-block; cursor: crosshair;">
                                        <canvas id="signature-pad" width="400" height="200" style="max-width: 100%; touch-action: none;"></canvas>
                                    </div>
                                    <div class="mt-2">
                                        <button type="button" class="btn btn-sm btn-outline-danger" id="clear_btn">
                                            <i class="fas fa-eraser"></i> Hapus / Ulangi
                                        </button>
                                    </div>
                                    {{-- Input Hidden untuk menyimpan data base64 --}}
                                    <input type="hidden" name="ttd_pemohon" id="ttd_pemohon_input">
                                </div>
                            </div>
                        </div>

                        <div class="row mt-4">
                            <div class="col-12 col-md-6 mb-2 mb-md-0">
                                <a href="{{ route('pengguna.dashboard') }}" class="btn btn-secondary btn-block btn-lg">
                                    <i class="fas fa-arrow-left"></i> Batal
                                </a>
                            </div>
                            <div class="col-12 col-md-6">
                                {{-- Tambahkan onclick untuk memproses tanda tangan --}}
                                <button type="submit" class="btn btn-primary btn-block btn-lg shadow-sm" onclick="prepareSignature(event)">
                                    <i class="fas fa-paper-plane"></i> Kirim Pengajuan
                                </button>
                            </div>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>

</div>

{{-- SCRIPT: Signature Pad & File Name --}}
@push('scripts')
{{-- CDN Signature Pad --}}
<script src="https://cdn.jsdelivr.net/npm/signature_pad@4.0.0/dist/signature_pad.umd.min.js"></script>

<script>
    // 1. Menampilkan nama file yang diupload di label custom-file
    $('.custom-file-input').on('change', function() {
        let fileName = $(this).val().split('\\').pop();
        $(this).next('.custom-file-label').addClass("selected").html(fileName);
    });

    // 2. Logika Signature Pad
    document.addEventListener("DOMContentLoaded", function() {
        var canvas = document.getElementById('signature-pad');
        var signaturePad = new SignaturePad(canvas, {
            backgroundColor: 'rgba(255, 255, 255, 0)', // Transparan/Putih
            penColor: 'rgb(0, 0, 0)' // Tinta Hitam
        });

        // Tombol Hapus
        document.getElementById('clear_btn').addEventListener('click', function () {
            signaturePad.clear();
        });

        // Fungsi saat tombol Submit ditekan
        window.prepareSignature = function(event) {
            var hiddenInput = document.getElementById('ttd_pemohon_input');

            if (signaturePad.isEmpty()) {
                alert("Harap melakukan tanda tangan terlebih dahulu!");
                event.preventDefault(); // Batalkan submit jika kosong
            } else {
                // Ambil data gambar dalam format Base64 dan masukkan ke input hidden
                var dataUrl = signaturePad.toDataURL('image/png');
                hiddenInput.value = dataUrl;
            }
        };

        // Resize Canvas agar responsif (Opsional, perbaikan tampilan di HP)
        function resizeCanvas() {
            var ratio =  Math.max(window.devicePixelRatio || 1, 1);
            canvas.width = canvas.offsetWidth * ratio;
            canvas.height = canvas.offsetHeight * ratio;
            canvas.getContext("2d").scale(ratio, ratio);
            signaturePad.clear(); // Bersihkan saat resize agar tinta tidak pecah
        }
        // window.addEventListener("resize", resizeCanvas); // Aktifkan jika ingin resize otomatis
    });
</script>
@endpush

@endsection